# 1. 파이토치(Pytorch)
* tensorflow와 함께 머신러닝, 딥러닝에서 가장 널리 사용되는 프레임워크
* 뉴욕대학교와 페이스북이 공동으로 개발하였고, 현재 가장 대중적이고 널리 사용되는 프레임워크
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 파이썬 기반으로 변경한 것이 Pytorch

In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


### 1-1. Tensor
* 텐서는 배열이나 행렬과 매우 유사한 특수 자료구조
* 파이토치는 텐서를 사용하여 모델의 입력과 출력, 모델의 매개변수들을 처리

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
import numpy as np

In [4]:
np_array = np.array(data)
x_np_1 = torch.tensor(np_array)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_np_1[0, 0] = 100
print(x_np_1)   # 새로운 텐서
print(np_array) # 기존 ndarray

tensor([[100,   2],
        [  3,   4]])
[[1 2]
 [3 4]]


In [6]:
x_np_2 = torch.as_tensor(np_array)  # ndarray와 동일한 메모리 주소를 가리키는 뷰를 만듦
print(x_np_2)
x_np_2[0, 0] = 200  # 기존 메모리 주소의 ndarray값을 변경하게됌
print(x_np_2)
print(np_array)

tensor([[1, 2],
        [3, 4]])
tensor([[200,   2],
        [  3,   4]])
[[200   2]
 [  3   4]]


In [7]:
x_np_3 = torch.from_numpy(np_array)  # ndarray와 동일한 메모리 주소를 가리키는 뷰를 만듦
print(x_np_3)
x_np_3[0, 0] = 400  # 기존 메모리 주소의 ndarray값을 변경하게됌
print(x_np_3)
print(np_array)

tensor([[200,   2],
        [  3,   4]])
tensor([[400,   2],
        [  3,   4]])
[[400   2]
 [  3   4]]


In [8]:
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[100   2]
 [  3   4]] <class 'numpy.ndarray'>


In [9]:
a = torch.ones(2, 3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
b = torch.zeros(2, 3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
c = torch.full((2, 3), 2)
print(c)

tensor([[2, 2, 2],
        [2, 2, 2]])


In [12]:
d = torch.empty(2, 3)
print(d)

tensor([[1.4013e-45, 0.0000e+00, 8.5595e-35],
        [0.0000e+00, 2.8026e-45, 8.4078e-45]])


In [13]:
e = torch.eye(5)
print(e)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [14]:
f = torch.arange(10)
print(f)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
g = torch.rand(2, 2)
print(g)

tensor([[0.4019, 0.6182],
        [0.3768, 0.0967]])


In [16]:
h = torch.randn(2, 2)
print(h)

tensor([[-0.1263, -0.5274],
        [-2.1469, -0.4515]])


### 1-2. Tensor 속성

In [17]:
tensor = torch.rand(3, 4)
print(f'shape : {tensor.shape}')
print(f'type : {tensor.dtype}')
print(f'device : {tensor.device}')

shape : torch.Size([3, 4])
type : torch.float32
device : cpu


### 1-3. GPU 사용하기
* 코랩에서 device 변경하는 방법
    * 상단 메뉴 → 런타임 → 런타임 유형변경 → 하드웨어 가속기를 GPU로 변경 → 저장 → 다시 시작 및 모두 실행

In [18]:
tensor = tensor.reshape(4, 3)
tensor = tensor.int()
if torch.cuda.is_available():
    print('GPU를 사용할 수 있음')
    tensor = tensor.to('cuda')

print(f'shape : {tensor.shape}')
print(f'type : {tensor.dtype}')
print(f'device : {tensor.device}')

GPU를 사용할 수 있음
shape : torch.Size([4, 3])
type : torch.int32
device : cuda:0


### 1-4. 인덱싱과 슬라이싱

In [20]:
a = torch.arange(1, 13).reshape(3, 4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [24]:
print(a[1])
print(a[0, -1])
print(a[1:-1])
print(a[:2, 2:])

tensor([5, 6, 7, 8])
tensor(4)
tensor([[5, 6, 7, 8]])
tensor([[3, 4],
        [7, 8]])


### 1-5. Transpose
* 두 개의 차원을 맞교환할 때 사용

In [25]:
a = torch.arange(16).reshape(2, 2, 4)
print(a, a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [26]:
b = a.transpose(1, 2)
print(b, b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


### 1-6. permute

In [27]:
# a → 2, 2, 4
c = a.permute((2, 0, 1)) # 4, 2, 2
print(c, c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


### 1-7. Tensor 연산

In [29]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(torch.add(x, y))
print(torch.subtract(x, y))
print(torch.multiply(x, y))
print(torch.divide(x, y))
print(torch.matmul(x, y))

tensor([[2., 4.],
        [6., 8.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[ 7., 10.],
        [15., 22.]])


In [32]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)

tensor([[2., 4.],
        [6., 8.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[ 7., 10.],
        [15., 22.]])


In [33]:
# in-place 연산
# ex) num += 1
print(x.add(y))
print(x)
print(y)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [35]:
print(x.add_(y)) # x에 결과를 다시 저장
print(x)
# 위 모든 연산자에 _를 붙여 사용할 수 있음

tensor([[ 3.,  6.],
        [ 9., 12.]])
tensor([[ 3.,  6.],
        [ 9., 12.]])


In [36]:
z = torch.arange(1, 11).reshape(2, 5)

sum1 = torch.sum(z, axis=0)
print(sum1, sum1.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])


In [37]:
sum2 = torch.sum(z, axis=1)
print(sum2, sum2.shape)

tensor([15, 40]) torch.Size([2])


In [38]:
sum3 = torch.sum(z, axis=-1)
print(sum3, sum3.shape)

tensor([15, 40]) torch.Size([2])


In [39]:
# 행렬 복사 + 붙여넣기
a = torch.arange(24).reshape(4, 6)
b = a.clone().detach()
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
